project_id       = "bulerez786"
region           = "us-central1"
service_name     = "medicine-forecast-service"
artifact_repo_name = "medicine-forecast"
repository_owner = "manish-karautia"
repository_name  = "Terraform_Medicine_Forecast"
